# Generated by Django 3.0.6 on 2020-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index_Id', models.IntegerField(default=0)),
                ('Email', models.EmailField(default=0, max_length=100)),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='cart')),
                ('Quantity', models.IntegerField()),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Weight1', models.CharField(max_length=20)),
                ('Sub_Total', models.IntegerField()),
                ('Status', models.IntegerField(default=0)),
                ('Order_Id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
