# Generated by Django 3.0.6 on 2020-07-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Weight',
            field=models.IntegerField(default=0),
        ),
    ]
