# Generated by Django 3.0.6 on 2020-08-02 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_Address',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Index_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
