# Generated by Django 3.0.6 on 2020-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_auto_20200802_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Order_Id',
            field=models.CharField(default='ABC', max_length=50, unique=True),
        ),
    ]
