# Generated by Django 3.0.6 on 2020-08-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0006_auto_20200802_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Date',
            new_name='Order_Date',
        ),
    ]
