# Generated by Django 3.0.6 on 2020-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0007_auto_20200806_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Time',
        ),
        migrations.AddField(
            model_name='order',
            name='Delivery_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
