# Generated by Django 3.0.6 on 2020-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0011_remove_cart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Index_Id',
            new_name='Pro_Id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Index_Id',
            new_name='Pro_Id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Delivery_Address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Delivery_Date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payment_Status',
        ),
        migrations.AddField(
            model_name='cart',
            name='Customer_Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Seller_Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Customer_Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Seller_Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Status_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Sub_Total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Weight1',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email_Id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
