# Generated by Django 3.1.1 on 2020-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govt',
            name='Land',
            field=models.CharField(max_length=20),
        ),
    ]
