# Generated by Django 3.1.1 on 2020-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20200919_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govt',
            name='Land',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
