# Generated by Django 3.0.6 on 2020-07-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='Email',
            field=models.EmailField(default=0, max_length=100),
        ),
    ]
