# Generated by Django 3.1.1 on 2020-09-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_auto_20200729_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Email_Id', models.EmailField(max_length=120)),
                ('Mobile_No', models.IntegerField(max_length=20)),
                ('Shop_Name', models.CharField(max_length=100)),
                ('Shop_Id', models.CharField(max_length=100)),
                ('Password', models.CharField(blank=True, max_length=20)),
                ('Address', models.TextField(max_length=200)),
            ],
        ),
    ]
