# Generated by Django 3.1.1 on 2020-09-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0003_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Mobile_No',
            field=models.IntegerField(),
        ),
    ]
